{% set version = "2.9.0" %}

# adapted from recipe in https://github.com/pytorch/builder
# TODO: examine if it is possible to link DSO dynamically
package:
  name: magma
  version: {{ version }}

source:
   url: https://icl.cs.utk.edu/projectsfiles/magma/downloads/magma-{{ version }}.tar.gz
   sha256: ff77fd3726b3dfec3bfb55790b06480aa5cc384396c2db35c56fdae4a82c641c
   patches:
    - thread_queue.patch
    - cmake_policy.patch

build:
  number: 0
  # we currently only need this for pytorch GPU, which currently only uses this for linux-64.
  # Windows CUDA support is being enabled - the build script includes CUDA configuration.
  skip: true  # [not ((win or linux) and x86_64)]
requirements:
  build:
    - {{ stdlib('c') }}
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ compiler('cuda') }}                                 # [gpu_variant == "cuda-12"]
    - make           # [not win]
    - cmake
    - ninja          # [win]
    - msys2-patch    # [win]
  host:
    - cudatoolkit {{ cudatoolkit }}*                         # [gpu_variant == "cuda-11"]
    - cuda-cudart-dev                                        # [gpu_variant == "cuda-12"]
    - cuda-profiler-api                                      # [gpu_variant == "cuda-12"]
    - libcublas-dev                                          # [gpu_variant == "cuda-12"]
    - libcusparse-dev                                        # [gpu_variant == "cuda-12"]
    - intel-openmp {{ mkl }}
    - mkl {{ mkl }}
    - mkl-include
  run:
    - {{ pin_compatible('cudatoolkit', max_pin='x.x') }}     # [gpu_variant == "cuda-11"]
    - intel-openmp {{ mkl }}
    - mkl {{ mkl }}

test:
  commands:
    - test -f $PREFIX/include/magma.h                             # [unix]
    - test -f $PREFIX/lib/libmagma${SHLIB_EXT}                    # [unix]
    - test -f $PREFIX/lib/libmagma_sparse${SHLIB_EXT}             # [unix]
    - if not exist %LIBRARY_PREFIX%\include\magma.h exit 1        # [win]
    - if not exist %LIBRARY_PREFIX%\lib\magma.lib exit 1          # [win]
    - if not exist %LIBRARY_PREFIX%\bin\magma.dll exit 1          # [win]
    - if not exist %LIBRARY_PREFIX%\lib\magma_sparse.lib exit 1   # [win]
    - if not exist %LIBRARY_PREFIX%\bin\magma_sparse.dll exit 1   # [win]

about:
  home: https://icl.utk.edu/magma
  license: BSD-3-Clause
  license_family: BSD
  license_file: COPYRIGHT
  summary: Matrix Algebra on GPU and Multicore Architectures
  description: |
    A new generation of linear algebra libraries that achieves the fastest possible time to an accurate solution on
    heterogeneous architectures, starting with current multicore + multi-GPU systems.
  doc_url: https://icl.utk.edu/projectsfiles/magma/doxygen/
  dev_url: https://github.com/icl-utk-edu/magma

extra:
  skip-lints:
    - host_section_needs_exact_pinnings
    - patch_unnecessary
