{% set version = "2.10.0" %}

package:
  name: magma
  version: {{ version }}

source:
   url: https://icl.cs.utk.edu/projectsfiles/magma/downloads/magma-{{ version }}.tar.gz
   sha256: ea0c57fcb64ac2fd7ffe8f02d8fe18f07055c5b7fba0164f565d1e3a85148fb5
   patches:
    - patches/thread_queue.patch

build:
  number: 0
  skip: true  # [not (win or linux)]
  overlinking_ignore_patterns:
    - "lib/libgomp.so*"    # [blas_impl == "openblas"]
    - "lib/libmagma*.so*"  # [blas_impl == "openblas"]
requirements:
  build:
    - {{ stdlib('c') }}
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ compiler('cuda') }}                                 # [cuda_compiler_version != "None"]
    - cmake
    - ninja
  host:
    - cuda-version {{ cuda_compiler_version }}               # [cuda_compiler_version != "None"]

    - cuda-cudart-dev                                        # [cuda_compiler_version != "None"]
    - cuda-profiler-api                                      # [cuda_compiler_version != "None"]
    - libcublas-dev                                          # [cuda_compiler_version != "None"]
    - libcusparse-dev                                        # [cuda_compiler_version != "None"]

    - intel-openmp {{ mkl }}  # [blas_impl == "mkl"]
    - mkl {{ mkl }}  # [blas_impl == "mkl"]
    - mkl-include  # [blas_impl == "mkl"]
    - mkl-devel {{ mkl }}  # [blas_impl == "mkl" and win]
    - libopenblas  # [blas_impl == "openblas"]
    - openblas-devel  # [blas_impl == "openblas" and win]

  run:
    - intel-openmp {{ mkl }}  # [blas_impl == "mkl"]
    - mkl {{ mkl }}  # [blas_impl == "mkl"]
    - libopenblas  # [blas_impl == "openblas"]
    - libgomp      # [blas_impl == "openblas"]

test:
  commands:
    - test -f $PREFIX/include/magma.h                             # [unix]
    - test -f $PREFIX/lib/libmagma${SHLIB_EXT}                    # [unix]
    - test -f $PREFIX/lib/libmagma_sparse${SHLIB_EXT}             # [unix]
    - if not exist %LIBRARY_PREFIX%\include\magma.h exit 1        # [win]
    - if not exist %LIBRARY_PREFIX%\lib\magma.lib exit 1          # [win]
    - if not exist %LIBRARY_PREFIX%\bin\magma.dll exit 1          # [win]
    - if not exist %LIBRARY_PREFIX%\lib\magma_sparse.lib exit 1   # [win]
    - if not exist %LIBRARY_PREFIX%\bin\magma_sparse.dll exit 1   # [win]

about:
  home: https://icl.utk.edu/magma
  license: BSD-3-Clause
  license_family: BSD
  license_file: COPYRIGHT
  summary: Matrix Algebra on GPU and Multicore Architectures
  description: |
    A new generation of linear algebra libraries that achieves the fastest possible time to an accurate solution on
    heterogeneous architectures, starting with current multicore + multi-GPU systems.
  doc_url: https://icl.utk.edu/projectsfiles/magma/doxygen/
  dev_url: https://github.com/icl-utk-edu/magma

extra:
  skip-lints:
    - host_section_needs_exact_pinnings
